-- 부모의 형질을 모두 보유한 대장균의 ID(ID), 대장균의 형질(GENOTYPE), 부모 대장균의 형질(PARENT_GENOTYPE)을 출력하는 SQL 문을 작성해주세요. 이때 결과는 ID에 대해 오름차순 정렬해주세요.
SELECT D2.ID, D2.GENOTYPE, D1.GENOTYPE 'PARENT_GENOTYPE'
FROM ECOLI_DATA D1, ECOLI_DATA D2
WHERE D1.ID = D2.PARENT_ID AND D1.GENOTYPE & D2.GENOTYPE = D1.GENOTYPE
ORDER BY ID;