-- 코드를 작성해주세요
SELECT SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E
JOIN (
        SELECT EMP_NO, SUM(SCORE) 'SCORE', RANK() OVER(ORDER BY SUM(SCORE) DESC) 'rnk'
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) G
ON E.EMP_NO = G.EMP_NO
WHERE rnk = 1;